{% set name = "escaping" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/escaping-{{ version }}.tar.gz
  sha256: 8c9efb9766ff8c63d6638d9f2423ffdf7e7e8cf570075fb6cea388c013547c0d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools ==68.0.0
    - pip
  run:
    - python >=3.7
    - emptylog >=0.0.4

test:
  imports:
    - escape
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pomponchik/escaping
  summary: Exception handling with universal interface for the decorator and context manager, built-in logging, and callbacks.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
