{% set name = "escaping" %}
{% set version = "0.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/escaping-{{ version }}.tar.gz
  sha256: c9faf884bfafe9dd791eb87c14881f575908f6487d767ed405a01434de07238d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools ==68.0.0
    - pip
  run:
    - python >={{ python_min }}
    - emptylog >=0.0.4

test:
  imports:
    - escape
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pomponchik/escaping
  summary: Exception handling with universal interface for the decorator and context manager, built-in logging, and callbacks.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
